### ISSUE TITLE
Add a tag when merging PRs

### ISSUE THREAD

**Issue by bbaassssiiee** [evandam/evandam.conda#10]
Please push a tag to github when PRs are merged. For usage without surprises I'd like to specify a version, for example **1.0.2**.

I use this command:
`ansible-galaxy install -r requirements.yml -p roles`

with this in the requirements.yml file:
```
---

- src: https://github.com/evandam/evandam.conda.git
  scm: git
  name: evandam.conda
  version: 1.0.2
```

With only **master** as the branch and no tags, I can obtain a change without notice.

**Comment by evandam** [comment]
Good point. I'll put together an initial release to get started and then maintain new versions as needed.

**Comment by evandam** [comment]
Feel free to use https://github.com/evandam/evandam.conda/releases/tag/v1.0 going forward!
